name: Deploy Firebase Rules

on:
  push:
    paths:
      - 'firebase/database.rules.json'
    branches: [main]

jobs:
  deploy-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only database
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
